// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';

export function GetAppDetails(arg1:string):Promise<Array<main.AppDetail>>;

export function GetCaptureStatus():Promise<Record<string, any>>;

export function GetHealthStatus():Promise<Record<string, any>>;

export function GetSessions():Promise<Array<storage.Session>>;

export function Greet(arg1:string):Promise<string>;

export function ToggleCapture(arg1:boolean):Promise<void>;
