// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {pipeline} from '../models';
import {types} from '../models';

export function GetAppDetails(arg1:string):Promise<Array<main.AppDetail>>;

export function GetCaptureStatus():Promise<pipeline.PipelineStats>;

export function GetHealthStatus():Promise<main.HealthStatusResponse>;

export function GetSessions():Promise<Array<types.Session>>;

export function Greet(arg1:string):Promise<string>;

export function ToggleCapture(arg1:boolean):Promise<void>;
