// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppDetails(arg1) {
  return window['go']['main']['App']['GetAppDetails'](arg1);
}

export function GetCaptureStatus() {
  return window['go']['main']['App']['GetCaptureStatus']();
}

export function GetHealthStatus() {
  return window['go']['main']['App']['GetHealthStatus']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ToggleCapture(arg1) {
  return window['go']['main']['App']['ToggleCapture'](arg1);
}
